### ISSUE TITLE
Long hyperlinks overlap on the next column

### ISSUE THREAD

**Issue by mickael-menu** [readium/readium-css#127]
I'm submitting a bug report

**Short description of the issue/suggestion:**

Long hyperlinks overlap on the next column, instead of being wrapped.

**Steps to reproduce the issue/enhancement:**

Unfortunately I cannot provide a free sample book. Contact me for exchanging it privately (note to self APP-428).

**Do you have screenshots, GIFs, demos or samples which demonstrate the problem or enhancement?** 

<img width="1024" alt="Screenshot 2023-06-09 at 14 43 01" src="https://github.com/readium/readium-css/assets/58686775/400f7b35-81f2-4c1a-b835-6213c6649674">

**Comment by JayPanoz** [comment]
Hmmm, that sounds like this is failing in safeguards – or is at least overridden by authors’ styles – then:

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/ReadiumCSS-safeguards.css#L37-L40

**Comment by danielweck** [comment]
moving https://github.com/readium/readium-css/issues/129
