### ISSUE TITLE
forcing "start" text alignment (left or right depending on document language) does not work with "inherit"

### ISSUE THREAD

**Issue by danielweck** [readium/readium-css#128]
In Thorium (Chromium web browser engine) we need this ReadiumCSS patch for the left/right (or start) override of justified text:

https://github.com/readium/r2-navigator-js/commit/aaaddf51d2c58b4e8b61da6eb5a9dc9a361ca057

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/user-settings-submodules/ReadiumCSS-textAlign_pref.css#L9-L16

**Comment by JayPanoz** [comment]
This is probably a CSS declaration we can add in ReadiumCSS to make it easier for everyone. 

With specs such as logical properties, values like `start` and `end` are meant to become more popular so that would future-proof ReadiumCSS a little bit.
