### ISSUE TITLE
Dist stylesheets and minification

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#132]
I'm submitting a topic for discussion.

**Short description of the issue/suggestion:**

When upgrading dev dependencies locally, I had to replace the PostCSS plugin for minification, `postcss-clean`, as it basically broke and errored the build process.

It wasn’t hard to find another one but, given times have changed and we’re now seeing people advise to even distribute sourcemaps so that it can be easier to debug, I’m wondering whether we should even minify the dist stylesheets in the first place and just let users do it on their own if they see it necessary.

**Comment by danielweck** [comment]
my take: let consumers of ReadiumCSS do it themselves. Nowadays I would use LightningCSS anyway, not PostCSS

https://github.com/parcel-bundler/lightningcss

**Comment by chocolatkey** [comment]
I agree with @danielweck - users of this project should take care of the minfication themselves. We should burden ourselves with being responsible for this, as there are two many possibilities to take into account. Would we include a sourcemap in the minified bundle? What format would the sourcemap be? What dependency would we use for this? etc.

The bundles should definitely still be made in my opinion, they are very helpful.

**Comment by mickael-menu** [comment]
>The bundles should definitely still be made in my opinion, they are very helpful.

Yep, I agree.
