### ISSUE TITLE
Fonts update

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#135]
I'm submitting a topic for discussion and its associated feature requests

**Short description of the issue/suggestion:**

It could be a good idea to review font-stacks and recommended fonts, and update them. There’s been a push to more legible typefaces lately e.g. [Luciole Vision](https://www.luciole-vision.com/luciole-en.html), and these may even be available as system fonts. 

On a related note, it would be worth adding a font-stack relying entirely on variable fonts, if possible. That would allow for user settings such as but not limited to fine-tuning the `font-weight` – I know some fonts may customise the aperture, etc.

**Comment by danielweck** [comment]
https://modernfontstacks.com/

shame about Android ....
