### ISSUE TITLE
Letter-spacing for japanese

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#136]
I'm submitting a topic for discussion.

**Short description of the issue/suggestion:**

`letter-spacing` has been [enabled as a user setting for Japanese in Thorium](https://github.com/readium/r2-navigator-js/commit/a93869041049a759d48c3be80661a0f10d1817d9) and I’m wondering if we should enable it globally in ReadiumCSS. 

At the time we first checked it was unclear whether it would help A11y-wise for CJK but feedback has been collected since and maybe we could improve on this front.

**Comment by HadrienGardeur** [comment]
Letter spacing has also been implemented in the Preferences API for Readium Mobile.

**Comment by JayPanoz** [comment]
Thanks for the quick feedback, I guess this pretty much answers this question then. 🙏

**Comment by danielweck** [comment]
just to be clear, Thorium has always offered letter-spacing but the issue was that ReadiumCSS was explicitly excluding Japanese, so we forced this.

**Comment by danielweck** [comment]
also, word-spacing for Japanese with wbr elements required CSS and JavaScript tricks to get working. it is a non-standard technique but it works for Thorium JA users.

**Comment by mickael-menu** [comment]
We have letter-spacing in the mobile toolkits [but it's only marked as "effective" with the default stylesheet](https://github.com/readium/kotlin-toolkit/blob/1570e80ab0a8f28255e53cabb291b1152f565a5f/readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubPreferencesEditor.kt#L492-L495) – so no CJK or RTL. We followed the [instructions from Readium CSS's doc](https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/docs/CSS12-user_prefs.md#right-to-left-scripts).

Let me know if it needs to be updated.

**Comment by mickael-menu** [comment]
If you need, I think you could reach out to these users for more insights with CJK:
* https://github.com/readium/swift-toolkit/discussions/370
* https://github.com/readium/kotlin-toolkit/issues/458

In particular, it looks like the paginated mode doesn't work as they expected.

**Comment by JayPanoz** [comment]
Some interesting issues from WCAG – looks like we’re not the only ones struggling on this topic: 

- [Does WCAG apply only to English (or the like), or does it aim to cover all languages?](https://github.com/w3c/wcag/issues/2680), which can be seen as a meta-issue of sorts given all the mentioned issues in the thread
- [Letter/Word spacing for CJK languages - SC 1.4.12 Text Spacing](https://github.com/w3c/wcag21/issues/677)
