### ISSUE TITLE
Space between words on RTL

### ISSUE THREAD

**Issue by vivekpshaligram** [readium/readium-css#152]
Could any one provide any additional references or solutions for adjusting word-spacing in RTL layout?

As it's mention it works on LTR layout only.

/** * Space between words. * * Only effective when: *  - the publication is reflowable *  - the layout is LTR */ val wordSpacing: RangePreference<Double> = RangePreferenceDelegate( getValue = { preferences.wordSpacing }, getEffectiveValue = { state.settings.wordSpacing ?: 0.0 }, getIsEffective = ::isWordSpacingEffective, updateValue = { value -> updateValues { it.copy(wordSpacing = value) } }, supportedRange = 0.0..1.0, progressionStrategy = DoubleIncrement(0.1), valueFormatter = percentFormatter(), )

**Comment by Shtibel** [comment]
Hi @JayPanoz 
Maybe I can help on this.
I am an expert with CSS RTL, Hebrew and Arabic have a really big user base, so it will be grate to have support for Word spacing and Letter spacing on RTL.
Can you send me exactly where you have an issue ?

**Comment by JayPanoz** [comment]
Thanks for your patience. 

So the overarching issue was that no one could really confirm to us whether these settings were used in RTL languages and if what browsers currently do is what one would expect – we’re just using CSS’ `letter-` and `word-spacing` behind the scenes, or whether it was a lot more complex than that. 

In practice, in the first case it’s one module to enable in ReadiumCSS’ RTL export and some docs to update. 

In the second case then guidance and examples would have to be provided so that I can take a look at how to do it with pure CSS.

**Comment by vivekpshaligram** [comment]
Thank you for the information. Could you please clarify what exactly you meant by using readium-css? I'm not sure how it should be applied or integrated, especially in terms of letter-spacing and word-spacing.

**Comment by JayPanoz** [comment]
ReadiumCSS, this repository, is the library of CSS styles that Thorium and Readium Toolkits (Kotlin, Swift, TypeScript/web) use to implement user settings. 

The user setting for `word-spacing` is a [simple set of declarations](https://github.com/readium/readium-css/blob/develop/css%2Fsrc%2Fmodules%2Fuser-settings-submodules%2FReadiumCSS-wordSpacing_pref.css), it's just that is it not exported for RTL at the moment. 

But if the CSS properties do what is expected by users for RTL, it can be added very quickly.

**Comment by Shtibel** [comment]
Hi @JayPanoz Please see the video attached
As you can see word-spacing works exactly the same in Hebrew as it works in English
So you can just export it for RTL and it will work

[screen-capture (21).webm](https://github.com/user-attachments/assets/250f849b-e69a-4eea-ac95-9a6c9a89c4a3)

**Comment by JayPanoz** [comment]
Word-spacing for RTL is now available in `develop` branch (so that’s version 2 of ReadiumCSS).

I’m expecting it will take some additional time for it to propagate and the setting be available in apps since they have to migrate to this new version of ReadiumCSS though.

**Comment by Shtibel** [comment]
Thank you @JayPanoz !
How long do you think it will take to see it is live on the Apps ?

**Comment by JayPanoz** [comment]
I know the migration is on the roadmap of Thorium and Readium Toolkits for the end of this year but let me check more precisely with their maintainers. 

I'll get back to you once I have more details.

**Comment by mickael-menu** [comment]
It will likely not be done before next year on the mobile toolkits. On the web toolkit it will be done very soon.

**Comment by Shtibel** [comment]
@mickael-menu Hi,
Is there a way that I can migrate it on my project Apps so I will be able to use the word-spacing on my RTL mobile Applications?
