### ISSUE TITLE
Pagination is broken on Safari in Version2 

### ISSUE THREAD

**Issue by fondoger** [readium/readium-css#154]
I'm submitting a bug report.

**Short description of the issue**

With the latest `develop` branch, the pagination is no longer working on Safari devices.

With the exactly same web page, the pagination is only not working for iOS devices:

- Safari iOS (os ver: 18.1) ❌                 (Vertical scrolling, non-paginated)
- Safari Desktop (os ver: 15.1) ❌         (Vertical scrolling, non-paginated)
- Chrome Desktop ✅                            (Horizontal scrolling, paginated)
- Firefox Desktop ✅                              (Horizontal scrolling, paginated)
 
 By manually setting `column-width: 45rem;` on root node, the pagination on Safari became normal.

**Comment by JayPanoz** [comment]
Thanks for reporting that, this is indeed critical. 

It looks like this would be the culprit: 

https://github.com/readium/readium-css/blob/7951735415df96b9574f5d75e91ae1668e3a01be/css/src/modules/ReadiumCSS-pagination.css#L17-L18

From [this commit](https://github.com/readium/readium-css/commit/56800182a2d07c682c4a3630a7478d72e2317b01). I can remember doing that while working on the initial implementation of auto-layout in Readium Playground so something went obviously wrong at that moment cos’ it should have been caught pretty easily. 

Will revert this commit and update ReadiumCSS.

**Comment by JayPanoz** [comment]
@fondoger sorry for this mishap. This should be fixed in v.2.0.0-alpha.3 but do not hesitate to let me know if that's not the case. Thanks again for the report.
