### ISSUE TITLE
Overrides classification

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#16]
Following a discussion related to the iOS implementation, we defined 4 types of overrides: 

1. chrome (UI);
2. chrome advanced;
3. user overrides;
4. user overrides UI.

It would be great if we could reach a consensus so that this classification can become some sort of recommendation. 

## Chrome

- reading modes
- paged/scrolled view

## Chrome advanced

- number of columns
- margins
- custom reading modes (background and text color)
- filters (darken and invert for night mode)

## User overrides

- font-family
- font-size

## User overrides advanced

- line-height
- text-align and hyphens (those two should work together)
- paragraph spacing
- paragraph indent
- letter-spacing
- word-spacing
- type scale
- all bold (that should probably be a typeface in the humanist stack though)
- no italics

Opinions? 

[edit] We’ll also probably have extra a11y-related settings e.g. “all bold”, “strip italics”, etc. That could be automatic flags we add when the user picks a theme or even a typeface, or advanced user overrides.

**Comment by HadrienGardeur** [comment]
I think the last two (currently labeled as "Undefined") should be listed under "User overrides advanced".

**Comment by JayPanoz** [comment]
Yeah, probably. I’ll edit so that we don’t have undefined, we can move settings if needed anyway.

**Comment by llemeurfr** [comment]
We also have to keep in mind that for certain user profiles, dyslexic people in particular, access to font-family, line-height, letter/word/paragraph-spacing and text-align will be of paramount importance and a very good UX will be required.

**Comment by JayPanoz** [comment]
And we don’t currently cover themes in this classification, which are a set of user overrides (both “normal” and advanced) e.g. there could be a theme with presets for dyslexia the user would then be able to customize/fine-tune.

**Comment by JayPanoz** [comment]
Added “a11y flags” (see edit)

An interesting development there is [variable fonts](https://medium.com/@clagnut/get-started-with-variable-fonts-c055fd73ecd7). 

Sadly there are still in their early days and support + catalog of fonts are lacking at the moment, but that could help tremendously with such flags. I.e. a conditional UI telling something like “Oh I can see you’re making the font bolder, do you wish to strip italics?”

**Comment by JayPanoz** [comment]
FYI I’m planning to modularize the user settings settings based on those categories. We indeed have quite a monolithic stylesheet at the moment and it’s all or nothing so, should implementers choose not to offer some settings, there’s a lot of removal to do at the moment (and we can probably help by providing them with more flexibility e.g. not using the advanced user overrides at all).

**Comment by JayPanoz** [comment]
This has been documented in the alpha version and can consequently be closed.
