### ISSUE TITLE
Provide custom font selection

### ISSUE THREAD

**Issue by typometre** [readium/readium-css#22]
As @JayPanoz stated in #4 about Installing extra fonts, this is actually a thing.
Users want to have control to meet their disability, preferences, taste…
Providing a Google fonts install in the reading app is a good thing but what will be better is to provide the list of fonts already aiviable in the system as most of the users would have already installed there their needed fonts.
It needs a work specific for each platform and implementation but will be the best way to provide users an install extra font features.

Most operating systems have a way to install custom fonts at a OS level so why do each app will reinvent the wheel and provide their on way to install font for their own use instead of just letting the user pick in the system installed fonts.
As an example, even iOS which was really close have add a way to install fonts through Apple configurator app and the process is even simpler through http://sub.pentacom.jp/custom-ios-fonts/ or an app like [Anyfont](https://itunes.apple.com/us/app/anyfont/id821560738?mt=8). Even font vendors like Myfonts eased the process with an [install function directly on the order page](http://meta.myfonts.com/post/80802984786/install-fonts-from-myfonts-on-ios-7-devices).
Before this, each app which want to give this option have done an install in app with the major drawback that the font was only aiviable in the app. Now with system install, all app could browse and pick a font from the system as other OS.
This is an example but most platform have this possibility. Its works to done for each one but this seems the way to go as users willing to install a custom fonts in their reading apps must probably have ever installed it on the system for use in other apps.

**Comment by llemeurfr** [comment]
This is interesting, I copy our iOS / Android developers @camill-a and @aferditamuriqi for advise.

**Comment by danielweck** [comment]
Note that the Electron-NodeJS-TypeScript-Desktop-Navigator (quite a mouthful!) supports system fonts, in addition to the pre-defined ReadiumCSS font stack. Including Wingdings ;)  (really!)
(tried and tested on OSX ... but should work just fine on Linux and Windows as well)

If time allows (probably not), I will add support for WebFonts (e.g. stylesheet URLs from https://fonts.google.com )

**Comment by JayPanoz** [comment]
After careful consideration, that could also help us deal with edge cases. 

Although we’re paying extra attention to the default/recommended typefaces (and their fallbacks in the font stacks), there will be edge cases. Thinking about old characters which were removed from say, the greek and cyrillic alphabets, local languages making use of diacritics that the country’s official language doesn’t use, or Unified Canadian Syllabics, for which our strategy is almost “Euphemia UCAS or nothing.” 

This reminds me of [Kobo’s warning](https://github.com/kobolabs/epub-spec#languages-other-than-english) for instance (emphasis mine): 

> Some glyphs do not render on most fonts. In cases where creators are unable to supply embedded fonts they can **insert a note into the front matter of their content instructing users to select the font Georgia**. It correctly renders the greatest set of scripts.

And there might be some cases for which the user must absolutely set a very specific font and can’t embed it.

**Comment by JayPanoz** [comment]
This issue has been moved to the apps’ tracker so that it can be more visible to app developers: 

- Readium Desktop: https://github.com/edrlab/readium-desktop/issues/86
- R2 Swift App (iOS): https://github.com/readium/r2-testapp-swift/issues/78
- R2 Kotlin App (Android): https://github.com/readium/r2-testapp-kotlin/issues/11

Please use those for further communication/discussion. Thanks!
