### ISSUE TITLE
doc packaged as EPUB, can we please have exploded / expanded / unzipped as well as?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-css#29]
`ReadiumCSS_docs.epub`:
https://github.com/readium/readium-css/blob/develop/docs/ReadiumCSS_docs.epub

@JayPanoz would it be possible please to store in the GitHub repository the extracted files of `ReadiumCSS_docs.epub`, for example inside a folder called `ReadiumCSS_docs`?
https://github.com/readium/readium-css/tree/develop/docs/ReadiumCSS_docs

This way, the Readium "cloud / web reader" won't have to load the entire 1.5+MB EPUB in memory:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Freadium%2Freadium-css%2Fdevelop%2Fdocs%2FReadiumCSS_docs.epub

Thanks! :)

**Comment by danielweck** [comment]
Also, for your information, this is the Readium2 "webpub manifest" JSON view:
https://readium2.herokuapp.com/pub/aHR0cHM6Ly9yYXdnaXQuY29tL3JlYWRpdW0vcmVhZGl1bS1jc3MvZGV2ZWxvcC9kb2NzL1JlYWRpdW1DU1NfZG9jcy5lcHVi/manifest.json/show/all
(`ReadiumCSS_docs.epub` is dynamically fetched from GitHub, via the RawGit proxy)

**Comment by JayPanoz** [comment]
Here you go → https://github.com/readium/readium-css/tree/e9e03f58171a56d34bbd05d3bc2148180d289833/docs/ReadiumCSS_docs

**Comment by danielweck** [comment]
...and another FYI, this is *EPUB.js* loading `ReadiumCSS_docs.epub` via the Readium webpub JSON:
https://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=https://readium2.herokuapp.com/pub/aHR0cHM6Ly9yYXdnaXQuY29tL3JlYWRpdW0vcmVhZGl1bS1jc3MvZGV2ZWxvcC9kb2NzL1JlYWRpdW1DU1NfZG9jcy5lcHVi/manifest.json

**Comment by danielweck** [comment]
Thanks @JayPanoz it works:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Freadium%2Freadium-css%2Fdevelop%2Fdocs%2FReadiumCSS_docs
:)

**Comment by JayPanoz** [comment]
Thanks! 

FYI I still have to align some parts of the doc with the current implementation, since we can now deal with it without any “iOS-implem” specific one. But I’ll update the docs ASAP (reviewed them this morning so I already know which parts I must edit).
