### ISSUE TITLE
Automatic hyphenation doesn’t work in Chrome Android, ChromeOS, Linux, and Windows

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#31]
While I can get `hyphens: auto` to work in Chrome Desktop, we just can’t get it to work in Chrome Mobile (including Web Views). 

Here’s what you can get on Desktop: 

![chrome-desktop](https://user-images.githubusercontent.com/12599652/36343482-2c2ad62c-140d-11e8-984a-43036b0ee289.png)

On mobile, it just won’t happen…

![screenshot_2018-02-17-18-03-53](https://user-images.githubusercontent.com/12599652/36343491-4258b41e-140d-11e8-9ddb-9720badae08e.png)

Even in landscape…

![screenshot_2018-02-17-18-04-24](https://user-images.githubusercontent.com/12599652/36343495-4ce468ec-140d-11e8-8aa5-0d22b8a5a323.png)

Tried changing the `lang` attribute from `en` to `en-US` to check if their mapping is super strict, to no effect. 

Checked other ebook apps, and got the same result: no hyphens.

It kinda drives me crazy as it is supposed to be supported in Chrome only on Android and Mac…

Links:

- [Chrome’s intent to ship](https://groups.google.com/a/chromium.org/forum/#!msg/Blink-dev/LsnvY7FFrY0/6xwNx-8SAgAJ)
- [Chromium bugs](http://crbug.com/new)
- [CanIUse](https://caniuse.com/#feat=css-hyphens)

**Comment by JayPanoz** [comment]
So yeah, it seems it doesn’t work in Android.

The only manual test they’ve made is checking [this link from a bug report](https://media.kulturbanause.de/2012/02/silbentrennung.html) to make sure it doesn’t crash Chrome Mobile… 

And here’s what I could get: 

![screenshot_2018-02-17-18-59-16](https://user-images.githubusercontent.com/12599652/36344110-bb18c846-1415-11e8-9944-2c50345fe5ad.png)

On a related note, [hyphens aren’t implemented on Windows, Linux ChromeOS yet.](https://bugs.chromium.org/p/chromium/issues/detail?id=652964)

So, question: do we want to just remove the setting from the non-iOS apps until they fix those issues? 

We manage that automatically when the `text-align` is set so should those issues be fixed, we’ll at least have that automatic handling.

**Comment by JayPanoz** [comment]
Bug reported. Here is the related [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=813414).

**Comment by JayPanoz** [comment]
Hyphen dicts available in Android 6.0.1 are: 

- English American (`en-US`)
- Basque (`eu`)
- Hungarian (`hu`)
- Armenian (`hy`)
- Norwegian Bokmal (`nb`)
- Norwegian Nynorsk (`nn`)
- Sanskrit (`sa`)
- Pan Ethiopian (`und-ethi`)

They’re available in `system/usr/hyphen-data` (and accessible with apps such as ES File Explorer). It would be a good idea to list the dicts available for each version.

**Comment by laudrain** [comment]
Nothing for French !

**Comment by JayPanoz** [comment]
Yeah, cc-ing @HadrienGardeur since we talked about that a few months ago and wondered whether we should embed ours. 

But if we can’t get Chrome to hyphenate in the first place…

**Comment by JayPanoz** [comment]
[Dicts can be found there for the current version of Android.](https://android.googlesource.com/platform/external/hyphenation-patterns/+/master/)

**Comment by JayPanoz** [comment]
Given this issue impacts Electron as well on non-MacOS platforms, we’d better discuss it during the next call. cc @llemeurfr 

Adding support would mean polyfilling this e.g. [Hyphenator.js](https://github.com/mnater/Hyphenator)

**Comment by llemeurfr** [comment]
So if I try to summarize, hyphenation support by a rendering engine depends on the platform, the language (dict or no dict). Polyfilling is doable, but the system should be smart enough to avoid loading the js if hyphenation is natively supported. 

I'll add that dyslexic user can't read with hyphenation on, therefore disabling hyphenation should be a user setting (advanced) and it should be disabled on some of the themes we'll provide.

**Comment by JayPanoz** [comment]
Also, after taking a quick look at hyphenator.js issues, I’d rather not recommend polyfilling it whenever possible, as it might create extra issues e.g. performance issues (all words have to be checked in the DOM and modified when a pattern is applicable) and a11y issues (screen readers have a hard time managing soft hyphens).

On a related note, implementers willing to support hyphenation in MS browsers will probably have to check stylesheets for `-ms-hyphens` and add it if it can’t be found (same issue as vertical writing i.e. filling the gaps for bad authoring practices).

**Comment by JayPanoz** [comment]
So the current version of Android embeds hyphenation dicts for…

- Assamese (`as`)
- Bulgarian (`bg`)
- Bengali (`bn`)
- Church Slavonic (`cu`)
- Welsh (`cy`)
- Danish (`da`)
- German (`de`)
- UK English (`en-GB`)
- American English (`en-US`)
- Spanish (`es`)
- Estonian (`et`)
- Pan-Ethiopic (`und-ethi`)
- Basque (`eu`)
- French (`fr`)
- Irish (`ga`)
- Gujarati (`gu`)
- Hindi (`hi`)
- Croatian (`hr`)
- Hungarian (`hu`)
- Armenian (`hy`)
- Kannada (`kn`)
- Malayalam (`ml`)
- Mongolian in the Cyrillic script (`mn-Cyrl`)
- Marathi (`mr`)
- Norwegian Bokmal (`nb`)
- Norwegian Nynorsk (`nn`)
- Oriya (`or`)
- Panjabi (`pa`)
- Portuguese (`pt`)
- Sanskrit (`sa`)
- Slovenian (`sl`)
- Tamil (`ta`) 
- Telugu (`te`)
- Turkmen (`tk`)

All seems to be retrieved from TeX (LaTeX).

**Comment by JayPanoz** [comment]
So, the good news is that a fix is on its way for Chrome Android: https://chromium-review.googlesource.com/c/chromium/src/+/927931

**Comment by JayPanoz** [comment]
As a recap of our discussion about the global issue during yesterday’s call…

- We can’t embed hyphenation dictionaries easily, since `@hyphenate-resource` has been removed from the CSS Text specification and was only implemented by an HTML2Print software
- We therefore have to rely on system dictionaries so, on Android, it means the user almost have to change its device to get more dictionaries (because system updates…)
- Polyfilling via JS is too costly, and is likely to create dev complications, performance, and **accessibility** issues (some screen readers cut the word where the soft-hyphen is and one word may become two or three)
- We consequently have to rely on browsers because both options are non-starters
- We will lobby for `hyphens` and dictionaries but can’t realistically do much more

There’s hope though, as the Chrome Android issue has been tackled within 24 hours, is currently being patched, helped discover other issues and even improve i18n hyphenation – it also proves one tiny R2 demo can go a loooong way.

So as soon as Chromium is able to fix the Windows issue (they’re relying on Microsoft it seems), things could go pretty fast.

**Comment by JayPanoz** [comment]
This has been documented in the alpha version and will be closed as soon as the Chromium bug reference in the third message is.

**Comment by JayPanoz** [comment]
Update: waiting for an Android 8.0 device (stock Oreo), which should be delivered this week, to confirm Chromium’s fix works because it currently doesn’t on an Android 6.0.1 device.

**Comment by HadrienGardeur** [comment]
I'm running 8.1, is there anything that I can easily test?

**Comment by JayPanoz** [comment]
Ah yes, that would help, thanks. The test can simply be r2-glue-js demo page in Chrome Canary (which is available on the App Store if you don’t have it already), they’ve been using it on their side to test the patch.

**Comment by JayPanoz** [comment]
So Hadrien could confirm the patch works, although word-spacing management is quite liberal. 

![screenshot_20180416-164030](https://user-images.githubusercontent.com/12599652/38817930-bc783634-4199-11e8-9aee-f486939461d1.png)

![screenshot_20180416-164037](https://user-images.githubusercontent.com/12599652/38817933-bee85232-4199-11e8-93a0-c7c3a458c196.png)

It would be nice if people could post on the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=813414) if they think this is too liberal. I’ll post an update there.

**Comment by JayPanoz** [comment]
As a proposed resolution at the Readium-CSS level, we should probably advise against putting an hyphen-specific user setting in the UI.

Further details: 

- we’re already managing hyphenation through `text-align` so it should not create an a11y issue since picking `left` in user settings will disable hyphenation automatically – even manual; 
- besides, there are languages for which dictionaries are not available anyway and there’s no way we can check that so we’re kinda getting around this issue by doing so;
- Chrome (hence Electron) on Windows is totally dependent on Microsoft releasing a public API so there’s probably some lobbying to do.

Which means I’ll have to make some doc changes before closing #37.

**Comment by JayPanoz** [comment]
So this is pretty much out of our hands now. We can close this issue since Chromium fixed it. 

Since hyphenation is the responsibility of browsers/rendering engines, please raise other hyphenation-related issues in their dedicated issue tracker: 

- [Chromium](https://bugs.chromium.org/p/chromium/issues/list) ([existing issue for Win, Linux and ChromeOS](https://bugs.chromium.org/p/chromium/issues/detail?id=652964))
- [Firefox’ Bugzilla](https://bugzilla.mozilla.org)
- [Webkit’s Bugzilla](https://bugs.webkit.org)
- [Microsoft EdgeHTML issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)

Thanks in advance.
