### ISSUE TITLE
Set up github pages

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#53]
**Short description of the issue/suggestion:**

We have a lot of docs in markdown form that could be published almost AS-IS, similar to what’s being done on https://github.com/readium/architecture.

**What is the expected behaviour?**

Docs + intro (ReadMe) available as a website i.e. readium.github.io/readium-css

**What is the current behaviour?**

You have to take a deep dive into the master branch to find the doc.

**What is the motivation / use case for changing the behaviour?**

It would be a lot more readable and easier to access.

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

Beware navigation across docs and links I guess.

**Comment by JayPanoz** [comment]
I guess there’s no way to have Previous/Next Doc linked at the bottom of every markdown file unless we “hardcode” that in the md, @HadrienGardeur?

We’ve been using the md files to generate an EPUB file so far… consequently, it would have to be removed if we keep on providing this EPUB file.

**Comment by HadrienGardeur** [comment]
@JayPanoz this feels a lot like a discussion about Web Publications ;-)

There's indeed no automatic way to have previous/next doc links by default (there's no such concept on the Web or on Github).
You'd have to manually add them and I guess hide them using CSS in the generated EPUB file.

If you'd like to get even more experimental, you could also go full WP on these pages and include a manifest + JS to generate such navigation.

**Comment by JayPanoz** [comment]
Well after some additional research, GitHub would probably answer this is what Jekyll is for, indeed.

I’ll check what the most sustainable option could be.

**Comment by llemeurfr** [comment]
Yes, Jekyll is the way to go. But it means moving the readium-css pages to the github.io repo IMO. We tried other ways (reference, inclusion) which were not practical.

**Comment by HadrienGardeur** [comment]
@llemeurfr you've missed the last two calls I think and during the first one, I actually started using the same Markdown files in architecture for the repo and the website at the same time: https://readium.org/architecture

IMO it is much better to avoid duplicating the effort of presenting these projects than forcing ourselves to use a separate repo just for the sake of keeping the design consistent with the same header/footer.

**Comment by JayPanoz** [comment]
Clarification: [Jekyll’s running behind the scenes](https://jekyllrb.com/docs/github-pages/) anyway, no? Only does it treat assets (.md files) as static when creating github pages as far as I can understand. 

So I was wondering if you could say use `include` without generating all the files it needs (i.e. overriding the hidden Github’s ones). That said, it won’t help with EPUB conversion but I can now remember I had to do some manual edits anyway…

**Comment by JayPanoz** [comment]
So yes it’s using Jekyll Default Layout, cf. 

- [Publishing with GitHub Pages, now as easy as 1, 2, 3](https://blog.github.com/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/)
- [Getting Started with GitHub Pages](https://guides.github.com/features/pages/)
- [Where does the head section come from when github pages generates source?](https://stackoverflow.com/questions/42597852/where-does-the-head-section-come-from-when-github-pages-generates-source)

**Comment by JayPanoz** [comment]
Alright got the default github-pages config running locally by [following those instructions](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-4-build-your-local-jekyll-site). 

Since I didn’t want to add this repo as origin yet, the trick is to create a `_config.yaml` file with `repository: <usr>/<local-repo-name>` so that `bundle exec jekyll serve` can run and serve the pages @ `localhost:4000`.

It’s my understanding everything is generated as static assets in a `_site` folder, cf. 

![capture d ecran 2018-09-21 a 13 20 20](https://user-images.githubusercontent.com/12599652/45878564-c9edf680-bda1-11e8-8b42-46f30348d304.png)

Note there’s only a CSS file added as an asset, no JS, nothing. 

I’ll try adding some stuff to see if you can build on top of the default config.

**Comment by JayPanoz** [comment]
Looks like you can so I’ll give it a deeper look next week. 

![capture d ecran 2018-09-21 a 13 39 03](https://user-images.githubusercontent.com/12599652/45879286-2e11ba00-bda4-11e8-8dac-0c31759f492a.png)

![capture d ecran 2018-09-21 a 13 39 22](https://user-images.githubusercontent.com/12599652/45879288-310caa80-bda4-11e8-9694-4ffe64054209.png)

There’s probably a way to handle that using templates so that includes don’t pollute markdown.

**Comment by JayPanoz** [comment]
Unless I’m missing something, which is quite possible given the amount of commits I’ve just made to correct paths and stuff, `master/docs` [must not follow the repository naming scheme <username>.github.io or <orgname>.github.io](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/). 

Problem is it automatically does when switching to `master/docs` as the source of github pages and will look for a CNAME in this folder. 

So I added a link in the ReadMe + an index in the `docs` folder with a TOC.

**Comment by JayPanoz** [comment]
BTW @llemeurfr, as quickly discussed with Hadrien through Slack, there may be a possibility to have the Readium.org layout/theme on all subdomain/project pages but that implies to [make it a theme available as a gem so that project pages can reference it in the Jekyll config](https://jekyllrb.com/docs/themes/) – or alternatively a repo on its own but I’m really not sure about this option.

**Comment by JayPanoz** [comment]
Setup done so an hypothetical update should be another issue.
