### ISSUE TITLE
Mixed NFD and NFC at misc/ReadiumCSS/ReadiumCSS-ebpaj_fonts_patch.css

### ISSUE THREAD

**Issue by toshiakikoike** [readium/readium-css#76]
I'm submitting a bug report
File:
readium-css/css/src/ReadiumCSS-ebpaj_fonts_patch.css

It seems mixed NFD and NFC.
Line 44 and 74.
For example;
line 72, "ギ" is "U+30AE" and "ゴ" is "U+30B4".
But line 74, "ギ" is "キ"(U+30AD )+"゙"(U+3099) and "ゴ" is "コ"(U+30B3)+"゙"(U+3099)

I converted this file to NFC,
https://github.com/toshiakikoike/readium-css/blob/master/css/src/ReadiumCSS-ebpaj_fonts_patch.css

(Sorry, I don't know how to pull request from out of project.)

**Comment by JayPanoz** [comment]
Thanks for the corrections, appreciated! 

I will update the file with a mention in the commit as soon as possible.
