### ISSUE TITLE
For Chinese publications, line head indent at the beginning of a paragraph usually uses two character width spaces

### ISSUE THREAD

**Issue by dotmonkey** [readium/readium-css#86]
**Short description of the issue/suggestion:**

For **Chinese** publications, line head indent at the beginning of a paragraph usually uses **two character width spaces**. Publications like magazines, with multi-column content and less text in each column, might apply a single character width line head indent at the beginning of paragraph as well.

**Steps to reproduce the issue/enhancement:**
None.

**What is the expected behaviour?**
Line head indent at the beginning of a paragraph is applied to **all** paragraphs. Nearly all books and magazines make use of this method.

**What is the current behaviour?**

Line head indent does not apply to the first paragraph but to the rest of the paragraphs. This method is mostly seen in **Western** publications.

**reference document:**
https://www.w3.org/TR/clreq/#line_head_indent_at_the_beginning_of_paragraphs

**Comment by JayPanoz** [comment]
Thanks for catching this. 

I can see I should correct:

- https://github.com/readium/readium-css/blob/master/css/src/ReadiumCSS-default-cjk-horizontal.css
- https://github.com/readium/readium-css/blob/master/css/src/ReadiumCSS-default-cjk-vertical.css

Will do later today in the develop branch and if I may, cc you so that you can check it’s fine for merging in master.

**Comment by dotmonkey** [comment]
> Thanks for catching this.
> 
> I can see I should correct:
> 
> * https://github.com/readium/readium-css/blob/master/css/src/ReadiumCSS-default-cjk-horizontal.css
> * https://github.com/readium/readium-css/blob/master/css/src/ReadiumCSS-default-cjk-vertical.css
> 
> Will do later today in the develop branch and if I may, cc you so that you can check it’s fine for merging in master.

I have test it, looks good. Thank you.
