### ISSUE TITLE
Add version in dist 

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#89]
I'm submitting a feature request

**Short description of the issue/suggestion:**

Currently there is no version to be found for/in dist stylesheets while it would probably make it easier for implementers to know they are up to date.

**Comment by JayPanoz** [comment]
@mickael-menu, @danielweck Question. 

I just resolved this issue in develop: https://github.com/readium/readium-css/commit/0849bc41f758ce515e346f75a96b8c51b293dcc6 and removed comments on the same occasion. 

Would you like to at least keep headers of (sub-)modules to make it a little easier to debug, or maybe even have map files in dist (they are currently .gitignored so the only way to get them is to build ReadiumCSS)?

**Comment by mickael-menu** [comment]
So far I didn't need to really debug inside Readium CSS itself, but the map files could be useful indeed. I have no opinion on the sub-modules headers, I guess it doesn't hurt to keep them.

**Comment by JayPanoz** [comment]
> I have no opinion on the sub-modules headers, I guess it doesn't hurt to keep them.

That’s reasonable, esp. considering #51, but at the same time map files would have all comments and point directly to these modules. 

Moreover, we’re not minifying ReadiumCSS stylesheets yet, and I guess it would be slightly better to do that eventually (as it’s pretty much a strong recommandation for web).

**Comment by danielweck** [comment]
FWIW: in the Readium Desktop SDK (i.e. all `r2-xxx-js`) components, we build a special data structure (JSON) to encode a persistent representation of "versioning information".
Example with the streamer:
http://readium2.herokuapp.com/version/show
https://github.com/edrlab/r2-streamer-js-dist/blob/develop/dist/gitrev.json
As you can see the `package.json` `version` field is not preserved, instead the canonical version is the Git revision.

**Comment by danielweck** [comment]
PS: here is the build script (crappy old, but has served us well over the years ;)

https://github.com/readium/r2-streamer-js/blob/develop/tools/gitrev.js
