### ISSUE TITLE
Paged vertical text book should be scrollable horizontally

### ISSUE THREAD

**Issue by kitanic** [readium/readium-css#96]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

Hello. 
I am testing readium-css to make my own EPUB viewer. There seems to be a very basic problem with the paged-mode of vertical layout.

In CJK vertical books, 'inline' text should be laid out vertically(up-to-bottom) but 'blocks' of page should be connected horizontally(right-to-left).
With paged mode of Thorium or test-app, I find the book scrolls page to page as vertically. This is a very unnatural behavior.

I can understand there is a technical difficulty on CSS multi columns but I think this is not permissible limitation.

Or is there a setting to fix it?

![vertical-layout](https://user-images.githubusercontent.com/3982249/97144729-4edd4280-17a8-11eb-96e0-055a187a65ff.png)

**Comment by danielweck** [comment]
Hello, there are known bugs with RTL Right To Left and VWM Vertical Writing Mode in Thorium, or more precisely in the Electron/TypeScript implementation of the Readium2 "navigator" component.
Here is for example an issue about pagination (there are problems with scrolling too, as you pointed out):
https://github.com/readium/r2-navigator-js/issues/42

**Comment by JayPanoz** [comment]
What Daniel said. 

We had a meeting about Japanese Layout back in 2017, which [led to lots of research summarised in this issue](https://github.com/rachelandrew/multicol-wip/issues/5) so if you’re using ReadiumCSS for pagination – and not your own pagination engine in JS – you have to fake it i.e. left/right swipe/navigation while columns are laid out on top of one another.

On iOS, the pagination API built on top of columns is using non-standard properties in Webkit to achieve that, but we have to support all major platforms – these props were removed in Chrome at the time they removed CSS regions. And it’s been clear they won’t ever be added into the CSS multicol spec, such issues belong to a CSS fragmentation module.

**Comment by kitanic** [comment]
CSS multi column may have difficult problem as I expected...

In my project, I think I will use customized Readium-css to suppress scroll animation and overflow: hidden. Without smooth animation, it dose not a matter if it scrolls vertically or horizontally because it looks as *warp*. Maybe some directional effect would help with accessibility as well.

Thank you for your response.
